<?php

declare(strict_types=1);

namespace Omega\Console\Commands;

use Omega\Console\AbstractCommand;
use Omega\Console\Attribute\AsCommand;
use Omega\Console\ConsoleApplication;
use ReflectionClass;
use Throwable;

use function array_unique;
use function array_values;
use function file_put_contents;
use function sort;

use const PHP_EOL;

#[AsCommand(
    name: 'command:map',
    description: 'Caches all console commands for faster resolution'
)]
class CommandMapCommand extends AbstractCommand
{
    /**
     * {@inheritdoc}
     */
    public function __invoke(): int
    {
        try {
            $consoleApp = new ConsoleApplication($this->app);
            $commands = $consoleApp->discoverCommands();
        } catch (Throwable $e) {
            $this->io->error('Failed to discover console commands: ' . $e->getMessage());

            return self::FAILURE;
        }

        if (empty($commands)) {
            $this->io->warning('No commands discovered.');
            return self::FAILURE;
        }

        $classShortNames = [];
        $shortNameClasses = [];

        foreach ($commands as $className) {
            $shortName = (new ReflectionClass($className))->getShortName();

            if (isset($shortNameClasses[$shortName]) && $shortNameClasses[$shortName] !== $className) {
                $this->io->error(
                    "Command cache aborted: short-name collision on '{$shortName}'"
                    . " between {$shortNameClasses[$shortName]} and {$className}."
                );

                return self::FAILURE;
            }

            $classShortNames[$className] = $shortName;
            $shortNameClasses[$shortName] = $className;
        }

        $uniqueClasses = array_unique(array_values($commands));
        sort($uniqueClasses);

        $content = "<?php" . PHP_EOL . PHP_EOL;
        $content .= "/**" . PHP_EOL;
        $content .= " * Generated by Omega Framework - Do not modify" . PHP_EOL;
        $content .= " */" . PHP_EOL . PHP_EOL;
        $content .= "declare(strict_types=1);" . PHP_EOL . PHP_EOL;

        foreach ($uniqueClasses as $className) {
            $content .= "use $className;" . PHP_EOL;
        }

        $content .= PHP_EOL . "return [" . PHP_EOL;

        foreach ($commands as $name => $className) {
            $content .= "    '$name' => {$classShortNames[$className]}::class," . PHP_EOL;
        }

        $content .= "];" . PHP_EOL;

        $cachePath = $this->app->getApplicationCachePath() . 'commands.php';

        try {
            $written = file_put_contents($cachePath, $content);
        } catch (Throwable $e) {
            $this->io->error('Failed to write cache file: ' . $e->getMessage());

            return self::FAILURE;
        }

        if (false === $written) {
            $this->io->error("Failed to write cache file at: {$cachePath}");

            return self::FAILURE;
        }

        $this->io->info("Command map successfully cached at: $cachePath");

        return self::SUCCESS;
    }
}
