<?php

declare(strict_types=1);

namespace Omega\Console\Commands;

use Omega\Console\AbstractCommand;
use Omega\Console\Attribute\AsCommand;
use Omega\Console\ConsoleApplication;
use Omega\Container\Exceptions\BindingResolutionException;
use Omega\Container\Exceptions\CircularAliasException;
use Omega\Container\Exceptions\EntryNotFoundException;
use Psr\Container\ContainerExceptionInterface;
use Psr\Container\NotFoundExceptionInterface;
use ReflectionClass;
use ReflectionException;
use Throwable;

use function array_unique;
use function array_values;
use function file_put_contents;
use function sort;

use const PHP_EOL;

#[AsCommand(
    name: 'command:map',
    description: 'Caches all console commands for faster resolution'
)]
class CommandMapCommand extends AbstractCommand
{
    /**
     * {@inheritdoc}
     *
     * @throws BindingResolutionException
     * @throws CircularAliasException
     * @throws ContainerExceptionInterface
     * @throws EntryNotFoundException
     * @throws NotFoundExceptionInterface
     * @throws ReflectionException
     */
    public function __invoke(): int
    {
        $consoleApp = new ConsoleApplication($this->app);
        $commands = $consoleApp->discoverCommands();

        if (empty($commands)) {
            $this->io->warning('No commands discovered.');
            return self::FAILURE;
        }

        $uniqueClasses = array_unique(array_values($commands));
        sort($uniqueClasses);

        $content = "<?php" . PHP_EOL . PHP_EOL;
        $content .= "/**" . PHP_EOL;
        $content .= " * Generated by Omega Framework - Do not modify" . PHP_EOL;
        $content .= " */" . PHP_EOL . PHP_EOL;
        $content .= "declare(strict_types=1);" . PHP_EOL . PHP_EOL;

        foreach ($uniqueClasses as $className) {
            $content .= "use $className;" . PHP_EOL;
        }

        $content .= PHP_EOL . "return [" . PHP_EOL;

        foreach ($commands as $name => $className) {
            $reflection = new ReflectionClass($className);
            $shortName = $reflection->getShortName();

            $content .= "    '$name' => $shortName::class," . PHP_EOL;
        }

        $content .= "];" . PHP_EOL;

        $cachePath = $this->app->getApplicationCachePath() . 'commands.php';

        try {
            file_put_contents($cachePath, $content);
            $this->io->info("Command map successfully cached at: $cachePath");
            return self::SUCCESS;
        } catch (Throwable $e) {
            $this->io->error("Failed to write cache file: " . $e->getMessage());
            return self::FAILURE;
        }
    }
}
