#!/usr/bin/env php
<?php

use Omega\Console\AbstractCommand;
use Omega\Console\Prompt;

require_once dirname(__DIR__, 4) . '/vendor/autoload.php';

$command = new class($argv) extends AbstractCommand {
    /**
     * @throws Exception Throw when a generic error occurred.
     */
    public function main(): void
  {    
    $prompt = new Prompt('test', [
      'test_1' => function () {
        echo "ok";
      },
      '' => function () {
        echo "default";
      }
    ]);      
    $prompt->option();
  }
};

$command->main();
